import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '../../..')

const SEMANTIC_CSS = resolve(ROOT, 'packages/tokens/src/semantic.css')
const GLOBAL_CSS = resolve(ROOT, 'packages/tokens/src/global.css')
const OUTPUT = resolve(ROOT, 'apps/theme-editor/src/token-definitions.ts')

interface TokenDef {
  name: string
  label: string
  type: 'color' | 'spacing' | 'radius' | 'shadow' | 'font-size'
  default: string
  group: string
}

function extractVarRefs(value: string): string[] {
  const refs: string[] = []
  const re = /var\(--y-[^)]+\)/g
  let m: RegExpExecArray | null
  while ((m = re.exec(value))) refs.push(m[0])
  return refs
}

function resolveToValue(
  varName: string,
  lightMap: Map<string, string>,
  globalMap: Map<string, string>,
): string {
  const raw = lightMap.get(varName) ?? globalMap.get(varName)
  if (!raw) return ''
  const refs = extractVarRefs(raw)
  if (refs.length === 0) return raw
  let resolved = raw
  for (const ref of refs) {
    const inner = ref.match(/var\((--y-[^)]+)\)/)?.[1]
    if (!inner) continue
    const val = resolveToValue(inner, lightMap, globalMap)
    if (val) resolved = resolved.replace(ref, val)
  }
  return resolved
}

function parseCssVars(filePath: string): Map<string, string> {
  const map = new Map<string, string>()
  let content: string
  try {
    content = readFileSync(filePath, 'utf-8')
  } catch {
    return map
  }
  const re = /(--y-[\w-]+)\s*:\s*([^;]+);/g
  let m: RegExpExecArray | null
  while ((m = re.exec(content))) {
    map.set(m[1], m[2].trim())
  }
  return map
}

function inferType(name: string): TokenDef['type'] {
  if (name.includes('color') || name.includes('ring') || name.includes('border') && !name.includes('radius'))
    return 'color'
  if (name.includes('radius')) return 'radius'
  if (name.includes('shadow')) return 'shadow'
  if (name.includes('space') || name.includes('font-size') || name.includes('line-height'))
    return 'spacing'
  if (name.includes('text') && /--y-text|--y-font/.test(name)) return 'font-size'
  return 'color'
}

function inferGroup(name: string): string {
  if (name.includes('color-primary') || name.includes('color-danger') ||
      name.includes('color-success') || name.includes('color-warning'))
    return 'colors'
  if (name.includes('color-bg')) return 'colors'
  if (name.includes('color-text') || name.includes('color-ring') || name.includes('color-border'))
    return 'colors'
  if (name.includes('shadow')) return 'shadows'
  if (name.includes('radius')) return 'radius'
  if (name.includes('space')) return 'spacing'
  if (name.includes('font') || name.includes('text') || name.includes('line-height'))
    return 'typography'
  return 'colors'
}

function toLabel(varName: string): string {
  return varName
    .replace(/^--y-/, '')
    .replace(/-/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

function main() {
  const lightMap = parseCssVars(SEMANTIC_CSS)
  const globalMap = parseCssVars(resolve(GLOBAL_CSS))

  const tokens: TokenDef[] = []
  const seen = new Set<string>()

  for (const [name] of lightMap) {
    if (seen.has(name)) continue
    seen.add(name)

    const resolved = resolveToValue(name, lightMap, globalMap)
    const type = inferType(name)
    const group = inferGroup(name)

    tokens.push({
      name,
      label: toLabel(name),
      type,
      default: resolved || lightMap.get(name)!,
      group,
    })
  }

  const groupOrder = ['colors', 'spacing', 'radius', 'shadows', 'typography']
  tokens.sort((a, b) => {
    const gi = groupOrder.indexOf(a.group) - groupOrder.indexOf(b.group)
    if (gi !== 0) return gi
    return a.name.localeCompare(b.name)
  })

  const groups = [
    { id: 'colors', label: 'Colors' },
    { id: 'spacing', label: 'Spacing' },
    { id: 'radius', label: 'Border Radius' },
    { id: 'shadows', label: 'Shadows' },
    { id: 'typography', label: 'Typography' },
  ] as const

  const output = `// Auto-generated by scripts/extract-tokens.ts — do not edit manually

export interface TokenDef {
  name: string
  label: string
  type: 'color' | 'spacing' | 'radius' | 'shadow' | 'font-size'
  default: string
  group: string
}

export const TOKEN_GROUPS = ${JSON.stringify(groups, null, 2)} as const

export const TOKENS: TokenDef[] = ${JSON.stringify(tokens, null, 2)}
`

  mkdirSync(dirname(OUTPUT), { recursive: true })
  writeFileSync(OUTPUT, output, 'utf-8')
  console.log(`Extracted ${tokens.length} tokens → ${OUTPUT}`)
}

main()
